create database PIZZA;
use pizza;
select * from pizza_sales;

SELECT COUNT(*)
FROM pizza_sales;
  
  --  KPI's 
  
-- 1. TOTAL REVENUE  
SELECT SUM(total_price)  as Total_Revenue FROM pizza_sales;

-- 2.  TOTAL ORDERS
SELECT COUNT(DISTINCT ORDER_ID) FROM pizza_sales;

-- 3. AVERAGE ORDER VALUE
SELECT CAST(CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2))/
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2) )AS DECIMAL(10,2)) 
AS AVG_ORDER_VALUE 
FROM PIZZA_SALES;

-- 4. TOTAL PIZZA SOLD
SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM  pizza_sales;

-- 5. AVERAGE PIZZA PER ORDER
SELECT SUM(QUANTITY)/COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;

select * from pizza_sales;

-- CHART REQUIREMENTS 

-- 1. MONTHLY TREND FOR TOTAL REVENUE
SELECT MONTHNAME(order_date) AS Month_Name,
       SUM(total_price) AS Revenue
FROM pizza_sales
GROUP BY MONTHNAME(order_date);

-- 2. DAILY TREND FOR TOTAL ORDERS
SELECT DAYNAME(order_date) AS DAY,
       COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM pizza_sales
GROUP BY DAYNAME(order_date);

-- 3. PERCENTAGE OF SALES BY PIZZA CATEGORY 
SELECT PIZZA_CATEGORY , CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_REVENUE , 
CAST(SUM(TOTAL_PRICE)*100/
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES )AS DECIMAL (10,2)) AS PERCENTAGE
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

-- 4. PERCENTAGE OF SALES BY PIZZA SIZE
SELECT PIZZA_SIZE ,  CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_REVENUE , 
CAST(SUM(TOTAL_PRICE)*100/
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES )AS DECIMAL (10,2)) AS PERCENTAGE
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

-- 5. TOTAL PIZZAS SOLD BY PIZZA SIZE AND CATEGORY
SELECT PIZZA_SIZE , SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

SELECT PIZZA_CATEGORY , SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

-- 6. REVENUE BY PIZZA NAME
SELECT PIZZA_NAME , CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2) ) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5 ;




-- TOP & BOTTOM ANALYSIS 

-- 1. TOP PIZZA BY REVENUE 
SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- 2. WORST PIZZA BY REVENUE 
SELECT PIZZA_NAME, CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2) )AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE 
LIMIT 5;

-- 3. TOP PIZZA BY ORDERS 
SELECT PIZZA_NAME ,  COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 5;

-- 4. WORST PIZZA BY ORDERS
SELECT PIZZA_NAME ,  COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS 
LIMIT 5;

-- 5. TOP PIZZA BY QUANTITY SOLD
SELECT PIZZA_NAME , SUM(QUANTITY) AS  TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC
LIMIT 5 ;

-- 6. BOTTOM  PIZZA BY QUANTITY SOLD
SELECT PIZZA_NAME , SUM(QUANTITY) AS  TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY_SOLD 
LIMIT 5 ;

select * from pizza_sales;

SHOW DATABASES;